### ISSUE TITLE
Support for new CIS Microsoft Azure Foundations Benchmark v1.5.0

### ISSUE THREAD

**Issue by sfunkernw** [turbot/steampipe-mod-azure-compliance#126]
In August 2022, CIS released a new version of their Azure benchmark:

- CIS Microsoft Azure Foundations Benchmark v1.5.0

I was surprised to see that the newly released CIS AWS 1.5.0 benchmark is already integrated in the AWS Compliance Mod.
Do you plan to integrate also the new CIS benchmark in the Azure Compliance Mod?

**Comment by rajlearner17** [comment]
@sfunkernw appreciate using Steampipe! 

We have it in the plan. We will keep you posted
