### ISSUE TITLE
Azure Compliance Mod NSG Evaluation 

### ISSUE THREAD

**Issue by akahub** [turbot/steampipe-mod-azure-compliance#137]
The NSG eval using the following query: https://github.com/turbot/steampipe-mod-azure-compliance/blob/main/query/network/network_security_group_rdp_access_restricted.sql 

..does not detect RDP 3389 being exposed if the protocol is set to Any. However, if the same port is used but with protocol TCP, this gets picked up by the compliance check.   

This means is that we may have rules set sing ANY protocol scattered around the environment which are not being detected.

**Comment by misraved** [comment]
Relevant slack thread - https://steampipe.slack.com/archives/C01UECB59A7/p1669302794872829

**Comment by misraved** [comment]
Fixed in https://github.com/turbot/steampipe-mod-azure-compliance/pull/138

**Comment by akahub** [comment]
@misraved thats amazing! I shall test this out in the next few days. Thank you

**Comment by misraved** [comment]
Thanks @akahub for the quick response 👍. Please let us know if you run into issues 👍 .
