### ISSUE TITLE
Add CIS Microsoft Azure Foundations Benchmark v2.0.0

### ISSUE THREAD

**Issue by rajlearner17** [turbot/steampipe-mod-azure-compliance#146]
**Is your feature request related to a problem? Please describe.**

Release - v2.0.0 - 02-14-2023

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by KingBrewer** [comment]
@rajlearner17 I appreciate your effort with the benchmarks. May I kindly ask if there's an ETA for the v2.0.0 to be supported?

**Comment by cbruno10** [comment]
Hi @KingBrewer , we're anticipating a release this upcoming Monday, March 20. This issue will automatically be resolved once the changes are merged in and a new version is cut.
