### ISSUE TITLE
Fix CIS v2.0.0 5.2.X by replacing alert.location = 'global' & removing additional alert.condition for 'resourceType'

### ISSUE THREAD

**Issue by KingBrewer** [turbot/steampipe-mod-azure-compliance#202]
**Describe the bug**
None of 5.2.1-5.2.10 checks work.
It appears to be related to the fact the queries to `azure_log_alert` table filter the alarm rules by location set to `Global` (one example: https://github.com/turbot/steampipe-mod-azure-compliance/blob/v0.31/regulatory_compliance/monitor.sp#L265), while the `location` and `region` values in the table are lower-case.

```SQL
+--------------------------------------+----------+--------+--------------------------------------------------------------------------------------------------------------------------------->
| type                                 | location | region | condition                                                                                                                       >
+--------------------------------------+----------+--------+--------------------------------------------------------------------------------------------------------------------------------->
| Microsoft.Insights/ActivityLogAlerts | global   | global | {"allOf":[{"equals":"Administrative","field":"category"},{"equals":"Microsoft.Sql/servers/firewallRules/write","field":"operatio>
| Microsoft.Insights/ActivityLogAlerts | global   | global | {"allOf":[{"equals":"Administrative","field":"category"},{"equals":"microsoft.network/publicipaddresses","field":"resourceType"}>
| Microsoft.Insights/ActivityLogAlerts | global   | global | {"allOf":[{"equals":"Security","field":"category"},{"equals":"Microsoft.Security/securitySolutions/delete","field":"operationNam>
| Microsoft.Insights/ActivityLogAlerts | global   | global | {"allOf":[{"equals":"Administrative","field":"category"},{"equals":"Microsoft.Authorization/policyAssignments/write","field":"op>
| Microsoft.Insights/ActivityLogAlerts | global   | global | {"allOf":[{"equals":"Administrative","field":"category"},{"equals":"Microsoft.Sql/servers/firewallRules/delete","field":"operati>
| Microsoft.Insights/ActivityLogAlerts | global   | global | {"allOf":[{"equals":"Administrative","field":"category"},{"equals":"Microsoft.Authorization/policyAssignments/delete","field":"o>
| Microsoft.Insights/ActivityLogAlerts | global   | global | {"allOf":[{"equals":"Administrative","field":"category"},{"equals":"Microsoft.Network/publicIPAddresses/write","field":"operatio>
| Microsoft.Insights/ActivityLogAlerts | global   | global | {"allOf":[{"equals":"Administrative","field":"category"},{"equals":"Microsoft.ClassicNetwork/networkSecurityGroups/delete","fiel>
| Microsoft.Insights/ActivityLogAlerts | global   | global | {"allOf":[{"equals":"Security","field":"category"},{"equals":"Microsoft.Security/securitySolutions/write","field":"operationName>
| Microsoft.Insights/ActivityLogAlerts | global   | global | {"allOf":[{"equals":"Administrative","field":"category"},{"equals":"Microsoft.Network/networkSecurityGroups/write","field":"oper>
+--------------------------------------+----------+--------+--------------------------------------------------------------------------------------------------------------------------------->
(END)

```

**Steampipe version (`steampipe -v`)**
v0.20.9

**Plugin version (`steampipe plugin list`)**
v0.31

**To reproduce**
- create activity log alarm rules as described in the CIS Benchmark document
- run `steampipe --mod-location steampipe-mod-azure-compliance check benchmark.cis_v200_5_2`
- none of the checks is passing

**Expected behavior**
All checks should pass. 

**Additional context**

After changing `alert.location = 'Global'` to `alert.location = 'global'` the checks appear to be passing validation

**Comment by KingBrewer** [comment]
What is notable, whilst testing the fix #203, even though the alerts can be fetched from the table, some checks are still don't work correctly. One of the examples is here: https://github.com/turbot/steampipe-mod-azure-compliance/blob/main/regulatory_compliance/monitor.sp#L475

In Azure there is no such a resource type that can be selected from the list whilst creating the alert, which renders the following line inapplicable:
`and alert.condition -> 'allOf' @> '[{"field": "resourceType", "equals": "microsoft.security/securitysolutions"}]'`

Resource types I couldn't find so far were:
- securitysolutions (https://github.com/turbot/steampipe-mod-azure-compliance/blob/main/regulatory_compliance/monitor.sp#L475)
- policyassignments (https://github.com/turbot/steampipe-mod-azure-compliance/blob/main/regulatory_compliance/monitor.sp#L269)
- networksecuritygroups/securityrules (https://github.com/turbot/steampipe-mod-azure-compliance/blob/main/regulatory_compliance/monitor.sp#L315)

**Comment by KingBrewer** [comment]
I've checked closer with the docs, and the audit procedures of checks in section 5.2 do not specify we need to be looking at certain categories of resources. In my opinion they should be deleted. The "resource categories" are present in the remediation procedure, but they don't really affect alert conditions, as the actual "signal" (i.e. operation name) is the only mandatory thing to make alerts being raised.

In my opinion the additional `and` statement is too restrictive, and combined with the fact some are no longer available through the Microsoft's UI it is a mistake to use them.


Example:
<img width="596" alt="image" src="https://github.com/turbot/steampipe-mod-azure-compliance/assets/18538056/691c387c-7b04-4ea6-befe-9547f568a9de">

**Comment by KingBrewer** [comment]
Here's my proposal how to fix the 5.2 section holistically: https://github.com/turbot/steampipe-mod-azure-compliance/compare/main...KingBrewer:cis-fix-5.2.x-2?expand=1

**Comment by rajlearner17** [comment]
@KingBrewer -- Responded in [PR](https://github.com/turbot/steampipe-mod-azure-compliance/pull/203#issuecomment-1655498640)

**Comment by KingBrewer** [comment]
With [v0.32](https://github.com/turbot/steampipe-mod-azure-compliance/releases/tag/v0.32) the issue is now considered resolved
