### ISSUE TITLE
Kubernetes Outdated Software Version Regex bug

### ISSUE THREAD

**Issue by fgomesz** [turbot/steampipe-mod-azure-compliance#232]
The regex of the Kubernetes Outdated Software query (https://hub.steampipe.io/mods/turbot/azure_compliance/queries/kubernetes_cluster_upgraded_with_non_vulnerable_version) is matching even the latest Kubernetes versions like 1.27.0.  Basically the regex used '1\.\d|10\.*' matches even the latest Kubernetes versions.

**To reproduce**
either use the steampipe query on a Kubernetes version 1.27.0 or newer, or use a postgres regex tester like
[Postgres regex tester](https://www.regexplanet.com/advanced/postgresql/index.html)

**Suggested fix**
Use this regex "1\.([0-9]|10)\.[0-9]{1,2}" instead of the '1\.\d|10\.*'

**Comment by khushboo9024** [comment]
@fgomesz  We appreciate your effort in identifying and reporting this bug. We will be releasing an updated version that addresses this issue as soon as possible.
Thanks!!
