### ISSUE TITLE
Azure CIS control 3.7 checking wrong parameter (?)

### ISSUE THREAD

**Issue by centralBellHop** [turbot/steampipe-mod-azure-compliance#276]
https://github.com/turbot/steampipe-mod-azure-compliance/blob/25b6fadae2b73f1cd61734cb7510325b942ccfef/regulatory_compliance/storage.sp#L374-L401

Azure CIS control 3.7 (v2.1.0): Ensure that 'Public Network Access' is `Disabled' for storage accounts

Control 3.7 checks whether a storage account is publicly accessible. The CIS-benchmark instructs to check whether the publicNetworkAccess parameter for that storage account is set to Disabled.

PowerPipe uses Query: storage_account_block_public_access to check 3.7 automatically. For reasons I don't understand, this query checks the allow_blob_public_access parameter. Note that this parameter is related to the blob, not to the storage account.

This results in a discrepancy between my automatic PowerPipe test and a manual test. I have a storage account, which has Public Access set to "Enabled". Within this storage account, the setting "Allow Blob anonymous access" is set to "Disabled". So the Blobs are not publicly accessible, but the overall storage accounts themselves are. This storage accounts, having enabled public access, should show up as an "Alarm" for CIS control 3.7. (Right?)

Running PowerPipe, control 3.7 returns "Okay", since the query checks the blob_public_access parameter, which is set to "Disabled". Control 3.7 should however return an "Alarm", since as described above, this storage account has Public Access enabled. I think this issue is caused by the Query checking the blob parameter instead of the storage account parameter.

Interestingly, CIS control 3.17 does concern the public accessibility of blobs, so I think the query used is checking 3.17. However, 3.17 has a different query (https://hub.powerpipe.io/mods/turbot/azure_compliance/queries/storage_account_blob_containers_public_access_private).

I might be completely wrong here, as Prowler has the exact same result. In that case, my apologies for misunderstanding something. I just find it strange that a manual check following the steps described in the CIS-benchmark results in a different outcome than the PowerPipe outcome.

**Comment by centralBellHop** [comment]
Tried some more things:

The Azure CLI script in CIS 3.7 is as follows:
`az storage account show --name <storage-account> --resource-group <resource-group> --query "{publicNetworkAccess:publicNetworkAccess}"`

Running this returns:
`"publicNetworkAccess": null`

According to [Microsoft Documentation](https://learn.microsoft.com/en-us/azure/templates/microsoft.storage/storageaccounts?pivots=deployment-language-bicep), the publicNetworkAccess parameter is a string, which can be "Enabled", "Disabled", or null. This documentation is unclear on what this parameter defaults to when empty, but since my Azure Portal shows that this toggle is set to "Enable access from all networks", I assume it defaults to "Enabled" when left empty. However, this might also just be the Azure Portal acting strange

**Comment by khushboo9024** [comment]
@centralBellHop Thanks for raising this issue. We have investigated from our side and confirmed that we are not checking the correct parameter. We need to check `public_network_access` (as per CIS) parameter. We will update the query and release a new version of compliance.
