### ISSUE TITLE
False positive being returned by mssql_managed_instance_vulnerability_assessment_enabled.sql check

### ISSUE THREAD

**Issue by durbin-git** [turbot/steampipe-mod-azure-compliance#79]
**Describe the bug**
When the `mssql_managed_instance_vulnerability_assessment_enabled.sql` statement is run as part of the `control.mssql_managed_instance_vulnerability_assessment_enabled` check, a false positive is returned due to the SQL statement incorrectly parsing the resulting JSON structure

**Steampipe version (`steampipe -v`)**
v0.9.1

**Plugin version (`steampipe plugin list`)**
Azure v0.20.0

**To reproduce**
Run the compliance check against a managed SQL instance that has periodic vulnerability scanning enabled.
The output will show an alarm and indicate that vulnerability scanning is disabled.

**Expected behavior**
The output should show the status as OK

**Additional context**

The SQL statement used to perform the check contains the following:

```
with vulnerability_assessments as (
  select
    distinct i.id as id
  from
    azure_mssql_managed_instance as i,
    jsonb_array_elements(vulnerability_assessments) a
    where
      a -> 'vulnerabilityAssessmentProperties' -> 'recurringScans' ->> 'isEnabled' = 'true'
      and a ->> 'name' = 'Default'
)
```

The returned JSON structure for an instance that has vulnerability scanning enabled is as follows:

```
{
     "id": "/subscriptions/[removed]
     "name": "Default",
     "type": "Microsoft.Sql/managedInstances/vulnerabilityAssessments"
     "recurringScans": {
         "emails": [
         ],
        "isEnabled": true,
         "emailSubscriptionAdmins": true
     },
     "storageContainerPath": "https://[removed].blob.core.windows.net/vulnerability-assessment/"
}
```

The vulnerabilityAssessmentProperties key does not exist in the returned structure and therefor line 8 of mssql_managed_instance_vulnerability_assessment_enabled.sql should be:

```
a -> 'recurringScans' ->> 'isEnabled' = 'true'
```

**Comment by rajlearner17** [comment]
@durbin-git thank you for using Steampipe. Good to see this feedback, as you mentioned, Azure changing the response, which may result to change certain queries. We will look into this and fix it soon.

**Comment by khushboo9024** [comment]
Hi @durbin-git thank you for your feedback. We were able to reproduce the bug, your assumption is correct, Azure has remove the key `vulnerabilityAssessmentProperties ` from response . We have fixed the query for now and also we are checking if the same issue exist for other queries as well.

The returned JSON structure of vulnerability assessments for an instance:
```
  "vulnerability_assessments": [
   {
    "id": "/subscriptions/d46d7416-f95f-4771-bbb5-529d4c76659c/resourceGroups/nist-test_group/providers/Microsoft.Sql/managedInstances/tets566/vulnerabilityAssessments/Default",
    "name": "Default",
    "recurringScans": {
     "emailSubscriptionAdmins": true,
     "isEnabled": true
    },
    "type": "Microsoft.Sql/managedInstances/vulnerabilityAssessments"
   }
  ]
```
The SQL query result:
```
  > with vulnerability_assessments as (
  select
    distinct i.id as id
  from
    azure_mssql_managed_instance as i,
    jsonb_array_elements(vulnerability_assessments) a
  where
    a -> 'recurringScans' ->> 'isEnabled' = 'true'
    and a ->> 'name' = 'Default'
)
select
  -- Required Columns
  s.id as resource,
  case
    when a.id is not null then 'ok'
    else 'alarm'
  end as status,
  case
    when a.id is not null then s.title || ' vulnerability assessment enabled.'
    else s.title || ' vulnerability assessment disabled.'
  end as reason,
  -- Additional Dimensions
  resource_group,
  sub.display_name as subscription
from
  azure_mssql_managed_instance as s
  left join vulnerability_assessments as a on s.id = a.id,
  azure_subscription as sub
where
  sub.subscription_id = s.subscription_id;
[
 {
  "reason": "tets566 vulnerability assessment enabled.",
  "resource": "/subscriptions/xxxx-xxx/resourceGroups/nist-test_group/providers/Microsoft.Sql/managedInstances/tets566",
  "resource_group": "nist-test_group",
  "status": "ok",
  "subscription": "xxxx"
 }
]

```
